### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by collinhundley** [vapor/redbird#31]
Redbird is not thread-safe, which causes problems when using it with Swift web frameworks. A single `Redbird` instance cannot be shared across the application, since multiple threads may require simultaneous access. Establishing a new connection for every request would be wasteful and silly.

This leaves us with two options:

1) Force the user to synchronize all calls to a shared `Redbird` instance. For example:

``` swift
dispatch_sync(com.myApp.redbirdSerialQueue) {
    redbird.command(...)
}
```

2) Account for thread safety within Redbird itself.  For example, `command()` may be synchronized as such:

``` swift
public func command(_ name: String, params: [String] = []) throws -> RespObject {
    dispatch_sync(com.redbird.serialQueue) {
        ...
    }
}
```

Correct me if I'm wrong (because I'm not familiar with the entire codebase), but concurrent access to a shared `Redbird` instance should be safe since none of its properties are mutated after initialization.

I personally believe that option 2 is much safer and easier. What do you think?  I can make the changes if you agree that thread safety should be addressed.

**Comment by czechboy0** [comment]
Hi @collinhundley,

Thanks for reaching out. You're right, currently Redbird has no guarantees of thread safety, so if you wish to use the same connection from multiple threads, I'd recommend to create a wrapper which ensures only one thread is calling into `command` at a time. 

The reason I don't want to add thread safety guarantees to Redbird is that GCD is not yet available is standard Swift snapshots on Linux, so the proposed solution would only work on Linux. If we'd want to synchronize access, we'd need to use a lower level technology that's either in the posix standard or in Foundation. 

Thus I'm not against adding synchronization, it just needs to be done with a technology that works on all our supported platforms (Darwin and Ubuntu right now)

**Comment by collinhundley** [comment]
Are we sure that Dispatch isn't available on Linux yet?  Kitura seems to be using it [here](https://github.com/IBM-Swift/Kitura-sys/blob/master/Sources/KituraSys/Queue.swift), and I know they're careful about maintaining Linux compatibility for all releases. I haven't had a chance to test it on Ubuntu yet though, so I can't say for certain.

**Comment by czechboy0** [comment]
Okay, let's hold off for now, we can pick this up again when Dispatch is bundled with the Linux toolchain.

**Comment by jtomanik** [comment]
Any plans to get back to thread safety now, when libdispatch is finally part of a Swift toolchains?

**Comment by czechboy0** [comment]
As we don't know exactly which commits will make it into Swift 3, I'd rather not spend too much energy on it until we have a Swift 3 GM.

**Comment by alokjha** [comment]
As Swift 3 is now official and libdispatch is available on Linux too , can thread safety now be added ?

**Comment by czechboy0** [comment]
@alokjha I thought about it more and I'm not sure that Redbird is the right place to do this. Each `Redbird` object represents one connection to the redis server, which can only be accessed from one thread at a time. So the responsibility of managing threads should lie in the application, not Redbird, I think.

**Comment by czechboy0** [comment]
@collinhundley To your original post, no, Redbird instances may NOT be accessed from multiple threads at the same time, since one instance has one socket descriptor of the socket connected to the database server. Each command consists of 1. sending a request and 2. receiving and parsing a response. So the sequence always has to be, for 3 separate commands ABC: `A1, A2, B1, B2, C1, C2`. If you accidentally use the same Redbird instance from two threads running two commands, and end up with something like `A1, B1, A2...`, the results are already undefined, since two threads are writing to/reading from a socket at the same time.

As mentioned in my comment above, I'm leaning towards your solution number 1, where the user is responsible over making access thread safe (which can mean many things: 1) create many connections, one for each thread, and get much better performance, or 2) have one connection, synchronize access from all threads to this instance, like you described above etc).

**Comment by tanner0101** [comment]
For reference, this was solved with `NSLock` in Vapor's Redbird wrapper (as @czechboy0 noted was possible).

https://github.com/vapor/redis-provider/pull/12
